version: "3.8"

services:
  api:
    build:
      context: .
      args:
        WORKDIR: $WORKDIR
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/backend"
    ports:
      - "3000:3000"
    environment:
      BASE_URL: "http://localhost:3000"
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password # mysql 8.0から必要になった
    restart: always # dockerデーモンとOSホストの再起動時にコンテナも再起動してくれる
    volumes: #コンテナー削除してもmysqlのデータを引き継げる
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: work_agile
    ports:
      - "4000:3306"
